// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/maydan-auth/ArenaRoster.tsx": () => import("../components/mockups/maydan-auth/ArenaRoster.tsx"),
  "./components/mockups/maydan-auth/ConversationalWizard.tsx": () => import("../components/mockups/maydan-auth/ConversationalWizard.tsx"),
  "./components/mockups/maydan-auth/Current.tsx": () => import("../components/mockups/maydan-auth/Current.tsx"),
  "./components/mockups/maydan-auth/GameFirst.tsx": () => import("../components/mockups/maydan-auth/GameFirst.tsx"),
  "./components/mockups/maydan-auth/IdentityDoors.tsx": () => import("../components/mockups/maydan-auth/IdentityDoors.tsx")
};
